apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170304994
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170304994
    app.kubernetes.io/part-of: test-app-170304994
  name: java-quarkus-170304994
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170304994
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170304994
    spec:
      containers:
      - image: quay.io/hacdev/plbk3v0v-tenant/test-app-170304994/java-quarkus-170304994@sha256:83d21ed0a4735f2227bb51925b9c5ed723b660a54be2f68285d0102b9f2f7cae
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
